name: APK Olusturucu
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Buildozer ile APK Uret
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_root: .

      - name: APK Dosyasini Yukle (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: NoxPlayer-APK
          path: bin/*.apk
          
