name: APK Oluşturucu
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Buildozer ile APK Üret
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_root: .

      - name: APK Dosyasını Yükle (Artifact)
        uses: actions/upload-artifact@v2
        with:
          name: NoxPlayer-APK
          path: bin/*.apk
          
